const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const output=path.resolve(process.env.TEST_OUTPUT_DIR||'test-results');fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{}),headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const email='ui-'+Date.now()+'@example.com',password='Local-test-123!';
 await page.goto('http://127.0.0.1:8765/');
 await page.locator('#email').fill(email);await page.locator('#pass').fill(password);await page.locator('#signup').click();
 await page.locator('#app').waitFor({state:'visible'});
 await page.locator('#searchOpp').fill('Cabo');await page.locator('#searchButton').click();
 await page.locator('.searchResult').first().waitFor({timeout:35000});await page.locator('.searchResult').first().click();
 await page.locator('#setupDetails').waitFor({state:'visible'});await page.locator('#confirmOpp').check();
 await page.locator('#setupExam').fill('2027-12-01');await page.locator('#setupMinutes').fill('180');
 await page.locator('#setupForm .btn').click();await page.locator('.task').first().waitFor();
 await page.waitForFunction(()=>document.getElementById('threeStatus').textContent==='3D activo');
 const frame=page.frameLocator('#pet3dFrame');await frame.locator('canvas').waitFor();
 assert(await frame.locator('canvas').evaluate(c=>c.width>0&&c.height>0));
 await page.route('**/api/tasks/*/complete',async route=>{await new Promise(r=>setTimeout(r,1200));await route.continue();});
 await page.locator('.check:not(:disabled)').first().click();await page.locator('#actualMinutes').fill('120');await page.locator('#saveTime').click();
 await page.getByText('Guardando…',{exact:true}).waitFor();
 assert(await page.evaluate(()=>audioContext.state==='running'),'Audio starts before the delayed server response');
 assert(await page.locator('.task.completed').count()===1);
 await page.getByText('Hecho hoy',{exact:true}).first().waitFor();
 await page.locator('.task').filter({hasText:'Test del bloque'}).locator('button').click();
 await page.locator('#testMinutes').fill('23');await page.locator('#scoreInput').fill('42');await page.locator('#saveScore').click();
 await page.getByText('Nota 42%',{exact:false}).waitFor();
 await page.reload();await page.getByText('Nota 42%',{exact:false}).waitFor();
 assert(await page.locator('.task.completed').count()===2);
 await page.waitForFunction(()=>document.getElementById('threeStatus').textContent==='3D activo');
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:path.join(output,'OpoRumbo-movil.png'),fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(output,'OpoRumbo-escritorio.png'),fullPage:true});
 await frame.locator('canvas').screenshot({path:path.join(output,'OpoRumbo-3D.png')});
 const second=await browser.newContext({viewport:{width:375,height:812}});const other=await second.newPage();
 await other.goto('http://127.0.0.1:8765/');await other.locator('#email').fill(email);await other.locator('#pass').fill(password);await other.locator('#signin').click();
 await other.getByText('Nota 42%',{exact:false}).waitFor();assert(await other.locator('.task.completed').count()===2);
 assert(await other.evaluate(()=>state.pacing.sessions.length===2));
 assert(await other.evaluate(()=>state.pacing.sessions.some(s=>s.actual_minutes===120)));
 await other.locator('[data-screen=Progress]').click();await other.locator('#estimateStatus').getByText('Estimación inicial',{exact:false}).waitFor();
 assert((await other.locator('#planMargin').textContent()).includes('h'));
 assert(await other.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await other.screenshot({path:path.join(output,'OpoRumbo-V19-Plan-movil.png'),fullPage:true});
 await other.setViewportSize({width:1440,height:1000});await other.screenshot({path:path.join(output,'OpoRumbo-V19-Plan.png'),fullPage:true});
 await other.setViewportSize({width:375,height:812});
 await other.locator('[data-screen=Profile]').click();await other.locator('#animSwitch').uncheck();
 await other.getByText('Cambios guardados.',{exact:true}).waitFor();await other.reload();await other.locator('[data-screen=Profile]').click();assert(!await other.locator('#animSwitch').isChecked());
 await other.locator('[data-screen=Today]').click();await other.waitForFunction(()=>document.getElementById('threeStatus').textContent==='3D activo');
 const pausedCanvas=other.frameLocator('#pet3dFrame').locator('canvas');
 const pausedA=await pausedCanvas.screenshot();await new Promise(r=>setTimeout(r,350));const pausedB=await pausedCanvas.screenshot();assert(pausedA.equals(pausedB),'Disabling animations freezes the 3D scene');
 // The original context is offline: keep an explicitly unconfirmed intent, retry safely.
 await context.setOffline(true);await page.locator('.check:not(:disabled)').first().click();await page.locator('#actualMinutes').fill('120');await page.locator('#saveTime').click();await page.locator('#retry').waitFor({state:'visible'});
 await context.setOffline(false);await page.locator('#retry').waitFor({state:'hidden'});await page.waitForFunction(()=>[...document.querySelectorAll('.saved')].filter(e=>e.textContent==='Hecho hoy').length===3);
 await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.task.completed').length===3);
 const cached=await page.evaluate(async()=>{const result=[];for(const key of await caches.keys()){for(const request of await (await caches.open(key)).keys())result.push(request.url);}return result;});assert(cached.every(url=>!url.includes('/api/')));
 // Block the 3D module in a fresh context; login and study must still work.
 const fallback=await browser.newContext({viewport:{width:320,height:700},serviceWorkers:'block'});
 await fallback.route('**/pet-scene.js*',route=>route.abort());const fp=await fallback.newPage();
 await fp.goto('http://127.0.0.1:8765/');await fp.locator('#email').fill(email);await fp.locator('#pass').fill(password);await fp.locator('#signin').click();
 await fp.locator('#tasks .task').first().waitFor();await fp.getByText('Vista sencilla',{exact:true}).waitFor();assert(await fp.locator('#petHero').isVisible());
 assert(await fp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await fp.locator('.check:not(:disabled)').first().click();await fp.locator('#actualMinutes').fill('18');await fp.locator('#saveTime').click();await fp.waitForFunction(()=>document.querySelectorAll('.task.completed').length===4);
 await fp.locator('#undoTask').click();await fp.waitForFunction(()=>document.querySelectorAll('.task.completed').length===3);
 await fp.screenshot({path:path.join(output,'OpoRumbo-fallback-320.png'),fullPage:true});
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({passed:true,checks:['V19 actual time survives independent login','V19 Plan mobile and desktop','UI registration and setup','real WebGL canvas','optimistic completion and audio before delayed server','test score 42 and reload','second independent session','animation preference persistence and frozen canvas','offline retry','no API cache','3D load failure fallback','undo last task','320/390/1440 layouts'],pageErrors:errors},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
